apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: sahiljangra/service-b:latest
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: tracing
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
