apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: tracing  # Use the namespace where Jaeger is deployed
spec:
  selector:
    app: jaeger  # Ensure this matches the labels on your Jaeger deployment/pod
  ports:
    - name: http
      protocol: TCP
      port: 16686       # Internal Jaeger UI port
      targetPort: 16686 # Port exposed by Jaeger container
      nodePort: 30010   # NodePort for external access (choose a unique value)
  type: NodePort
