apiVersion: v1
kind: Service
metadata:
  name: expose-servic-a
  namespace: tracing  # Use the namespace where service-a is deployed
spec:
  selector:
    app: service-a  # Ensure this matches the labels on your service-a deployment/pod
  ports:
    - name: http
      protocol: TCP
      port: 5000       # Internal port of service-a
      targetPort: 5000 # Port exposed by the service-a container
      nodePort: 30020  # NodePort for external access (choose a unique value)
  type: NodePort
